server:
  port: 8001

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sunCloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qilin.entities
  configuration:
    map-underscore-to-camel-case: true