server:
  port: 9000
spring:
  application:
    name: nacos-order-consume
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
    sentinel:
      transport:
        dashboard: http://localhost:8088
        port: 8719



service-url:
  nacos-user-service: http://nacos-pay-provider
feign:
  sentinel:
    enabled: true
