server:
  port: 8000

logging:
  level:
    com.qilin.apis.*: debug

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: cloud-consumer-order-feign
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: false
    openfeign:
      client:
        config:
          default:
            connect-timeout: 30000
            read-timeout: 30000
#          cloud-provider-payment:
#            connect-timeout: 3000
#            read-timeout: 3000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 2048
        response:
          enabled: true
      circuitbreaker:
        enabled: true
#        group:
#          enabled: true

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # 采样率,默认值0.1(就是10%的链路会被记录下来)


# 基于次数的降级
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # 默认1s
#  circuitbreaker: # 降级熔断
#    configs:
#      default:
#        failure-rate-threshold: 50 # 调用失败达到50%后打开断路器
#        sliding-window-type: count_based # 滑动窗口类型
#        sliding-window-size: 6 # 滑动窗口大小 count_based6个请求 time_base6秒
#        minimum-number-of-calls: 6 # 每个滑动窗口的周期
#        automatic-transition-from-open-to-half-open-enabled: true # 开始过度到半开状态
#        wait-duration-in-open-state: 5s # 从开启到半开启需要5s
#        permitted-number-of-calls-in-half-open-state: 2 #半开状态允许通过的最大请求数
#        record-exceptions:
#          - java.lang.Exception
#    instances:
#      cloud-provider-payment:
#        base-config: default



#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # 默认1s
#  bulkhead: # 信号量舱壁
#    instances:
#      cloud-provider-payment:
#        maxWaitDuration: 0s
#        maxConcurrentCalls: 20

#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # 默认1s 超过1s直接降级 (坑)
#  thread-pool-bulkhead: # 线程池
#    configs:
#      default:
#        max-thread-pool-size: 1
#        core-thread-pool-size: 1
#        queue-capacity: 1
#    instances:
#      cloud-provider-payment:
#        base-config: default


resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 20 # 一次刷新周期内允许最大的请求数
        limit-refresh-period: 1s # 刷新周期
        timeout-duration: 1 # 默认等待时间
    instances:
      cloud-provider-payment:
        base-config: default