server:
  port: 8000

logging:
  level:
    com.qilin.apis.*: debug

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: cloud-consumer-order-feign
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: false
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
          cloud-provider-payment:
            connect-timeout: 3000
            read-timeout: 3000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 2048
        response:
          enabled: true
      circuitbreaker:
        enabled: true
        group:
          enabled: true


# 基于次数的降级
resilience4j:
  circuitbreaker: # 降级熔断
    configs:
      default:
        failure-rate-threshold: 50 # 调用失败达到50%后打开断路器
        sliding-window-type: count_based # 滑动窗口类型
        sliding-window-size: 6 # 滑动窗口大小 count_based6个请求 time_base6秒
        minimum-number-of-calls: 6 # 每个滑动窗口的周期
        automatic-transition-from-open-to-half-open-enabled: true # 开始过度到半开状态
        wait-duration-in-open-state: 5s # 从开启到半开启需要5s
        permitted-number-of-calls-in-half-open-state: 2 #半开状态允许通过的最大请求数
        record-exceptions:
          - java.lang.Exception
    instances:
      cloud-provider-payment:
        base-config: default

